ARG BASE_IMAGE
ARG BUILDER_IMAGE


FROM $BUILDER_IMAGE AS builder
RUN apt update && apt install --no-install-recommends -y make
COPY . /app
WORKDIR /app
RUN make bin/registry

FROM $BASE_IMAGE
COPY --from=builder /app/bin/registry /usr/bin/registry
EXPOSE 5000
ENTRYPOINT ["registry"]
CMD ["serve", "/etc/docker/registry/config.yml"]
